site_name: bioregions
site_description: Serving BioRegional Data via API
repo_url: https://github.com/BioHarmony/BioRegionAPIs
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/BioHarmony">BioHarmony</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
