site_name: bioregions
site_description: Serving BioRegional Data via API
repo_url: https://github.com/BioHarmony-Foundation/BioRegionAPIs
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/BioHarmony-Foundation">BioHarmony Foundation</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Coordinates: 'api/coordinates.md'
